[package]
name = "shiguredo_libcamera"
version = "2026.1.0-canary.0"
edition = "2024"
rust-version = "1.88"
authors = ["Shiguredo Inc."]
license = "Apache-2.0"
description = "Safe Rust bindings for libcamera"

[dependencies]
shiguredo_libcamera_sys = { path = "../libcamera-sys" }

[dev-dependencies]
nojson = "0.3"
