[package]
name = "shiguredo_libcamera_sys"
version = "2026.1.0-canary.0"
edition = "2024"
rust-version = "1.88"
authors = ["Shiguredo Inc."]
license = "Apache-2.0"
description = "Raw FFI bindings for libcamera via C wrapper"
links = "camera_wrapper"

[build-dependencies]
bindgen = "0.72"
cc = "1"
pkg-config = "0.3"
